language: python

dist: trusty

notifications:
  email: false

env:
  global:
    - PY_VENV=$TRAVIS_BUILD_DIR/venv
    - PYTHON=$PY_VENV/bin/python

python:
  - "3.6"
  - "3.7-dev"

install:
  - python -m venv $PY_VENV
  - $PYTHON -m pip install -U pip wheel setuptools
  - $PYTHON -m pip install -r requirements.txt

before_script:
  - $PYTHON setup.py install

script:
  - cd /tmp
  - $PYTHON -m pickle5.test.test_pickle
